# Data exploration and preparation for analysis

citation() 
rm(list=ls(all=TRUE))


# Data----

library(ggplot2)
library(tidyverse)

Benth <- read.csv("Data/Benth_macroinv_data.csv", header=T)

str(Benth)

# make "System" as a factor
Benth <- Benth %>%
  mutate(System_id = as_factor(System)) %>% 
  mutate(Year = as_factor(Year)) %>% 
  select(-System, -Study.site)

str(Benth)

# Sample size per system type
table(Benth$System_type)
table(Benth$System_type, Benth$Country)
table(Benth$System_type, Benth$Country, Benth$Year)


ggplot(Benth, aes(x = System_type, y = SR)) +
  geom_boxplot()

ggplot(Benth, aes(x = System_type, y = Abund)) +
  geom_boxplot()



# Riparian zone variables ----
# Surrounding (riparian zone) variables
# the percentage of land use types in riparian zones of study systems. 
# Data are generated by Duška: on land use types in a radius of 50 m around sampling sites, 
# and there are four land use types: 
# wetlands, water bodies, forest and semi natural areas and agricultural areas. 
# Agricultural areas should be excluded as the effects of agriculture are included in HII. 
# The idea was to focus on the percentage of natural areas in the riparian zone (as some kind of buffer).


Benth$Wetlands
Benth$Water_bodies
Benth$Forests  # Forest and semi natural areas
Benth$Agricultural

# Add combined variables indicating the percent of natural areas in the riparian zone
# FRESHWATERS = Wetlands + Water_bodies; 
# Forests should be considered separately.
# or
# Natural_areas = Wetlands + Water_bodies + Forests

Benth <- Benth %>% 
  mutate(Freshwaters = Wetlands + Water_bodies,
         Natural_areas = Wetlands + Water_bodies + Forests)


# Correlations----

names(Benth)

# make average across study systems
Benth_aver <- Benth %>% 
  group_by(System_id) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  select(-System_id, -Area_m2,
         -Abund, -SR, -H, -FRic, -FEve, -FDiv, - FDis, -RaoQ)

str(Benth_aver)


corl <- round(cor(Benth_aver, use="pairwise.complete.obs", method = c("pearson")),2)
corl

write.csv(corl, "Results/correlation.csv",  row.names = T)

# as Excel (openxlsx)
# write.xlsx(corl, file="Resuts/correlation_r.xlsx")

# plot correlations

library(ggcorrplot)

x11(height=9,width=8.5)
ggcorrplot(corl, hc.order = F, type = "lower",
           lab = TRUE, lab_size = 2, tl.cex = 9,
           colors = c("red", "white", "blue"))

library(corrplot)
x11(height=9,width=8.5)
corrplot(corl, type = "upper",  
         tl.col = "black", tl.srt = 50)



# PCA----

library(factoextra)

names(Benth)

## water properties----

Water_prop <- Benth %>% 
  select(Tem, EC, DO, BOD, NO3.N, NH4.N, PO4.P, Chl.a)

pca1 <- prcomp(Water_prop, scale = T)
summary(pca1)
fviz_eig(pca1)
# select 3 PCs; 0.7388 Proportion of Variance explained
pca1


res.var1 <- get_pca_var(pca1)
res.var1$coord          # Coordinates
res.var1$contrib        # Contributions to the PCs
res.var1$cor            # Correlations with the PCs


# plot contributions of each variable to the PCs

library("corrplot")

col <- colorRampPalette(c("#00AFBB", "#E7B800", "#FC4E07"))

# res.var1$contrib[,1:3]  for first 3 PCs
corrplot(res.var1$contrib[,1:3], is.corr=F,  method="color", 
         col=col(6),  
         # type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of contribution
         tl.col="black", tl.srt=45, #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
           mar = c(0,0,0,0))

# plot correlations of each variable with the PCs
# res.var1$cor[,1:3]  for first 3 PCs

col2 <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

corrplot(res.var1$cor[,1:3], is.corr=F,  method="color", 
         col=col2(200),  
         #type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of correlation
         tl.col="black", tl.srt=45,  #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
         mar = c(0,0,0,0))

Benth_PCA1_ <- get_pca_ind(pca1)$coord[,1:3] #nutrients & properties
Benth_PCA1 <- bind_cols(Benth, Benth_PCA1_)%>% 
  rename(Water_PC1=Dim.1, Water_PC2=Dim.2, Water_PC3=Dim.3)
write_csv(Benth_PCA1, "Results/Benth_PC_water.csv")


## human impact----
names(Benth)

HI_prop <- Benth %>% 
  select(Agriculture_m, Highway_m, Waste.effluent,  # Solid_waste, 
         Gravel_eff)

pca2 <- prcomp(HI_prop, scale = T)
summary(pca2)
fviz_eig(pca2)
# select 3 PCs; 0.9248 Proportion of Variance explained
pca2


res.var2 <- get_pca_var(pca2)
res.var2$coord          # Coordinates
res.var2$contrib        # Contributions to the PCs
res.var2$cor            # Correlations with the PCs


# plot contributions of each variable to the PCs

library("corrplot")

col <- colorRampPalette(c("#00AFBB", "#E7B800", "#FC4E07"))

corrplot(res.var2$contrib[,1:3], is.corr=F,  method="color", 
         col=col(6),  
         # type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of contribution
         tl.col="black", tl.srt=45, #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
         mar = c(0,0,0,0))

# plot correlations of each variable with the PCs
col2 <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

corrplot(res.var2$cor[,1:3], is.corr=F,  method="color", 
         col=col2(200),  
         #type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of correlation
         tl.col="black", tl.srt=45,  #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
         mar = c(0,0,0,0))

Benth_PCA2_ <- get_pca_ind(pca2)$coord[,1:3] 
Benth_PCA2 <- bind_cols(Benth_PCA1, Benth_PCA2_) %>% 
  rename(HI_PC1=Dim.1, HI_PC2=Dim.2, HI_PC3=Dim.3)
write_csv(Benth_PCA2, "Data/Benth_PCA2.csv")


## combined HI & water properties----
names(Benth)

HI_Watr_prop <- Benth %>% 
  select(Agriculture_m, Highway_m, Waste.effluent,  # Solid_waste, 
         Gravel_eff,
         Tem, EC, DO, BOD, NO3.N, NH4.N, PO4.P, Chl.a)

pca3 <- prcomp(HI_Watr_prop, scale = T)
summary(pca3)
fviz_eig(pca3)
# select 3 PCs; 0.9248 Proportion of Variance explained
pca3


res.var3 <- get_pca_var(pca3)
res.var3$coord          # Coordinates
res.var3$contrib        # Contributions to the PCs
res.var3$cor            # Correlations with the PCs


# plot contributions of each variable to the PCs

library("corrplot")

col <- colorRampPalette(c("#00AFBB", "#E7B800", "#FC4E07"))

x11(height=9,width=8.5)
corrplot(res.var3$contrib[,1:4], is.corr=F,  method="color", 
         col=col(6),  
         # type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of contribution
         tl.col="black", tl.srt=45, #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
         mar = c(0,0,0,0))

# plot correlations of each variable with the PCs
col2 <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

x11(height=9,width=8.5)
corrplot(res.var3$cor[,1:4], is.corr=F,  method="color", 
         col=col2(200),  
         #type="lower", # order="hclust", 
         addCoef.col = "black", number.cex = 0.7, # Add coefficient of correlation
         tl.col="black", tl.srt=45,  #Text label color and rotation
         cl.cex = 0.7, cl.pos = "r", cl.align.text= "l",
         mar = c(0,0,0,0))

Benth_PCA3_ <- get_pca_ind(pca3)$coord[,1:4] 
Benth_PCA3 <- bind_cols(Benth, Benth_PCA3_)
write_csv(Benth_PCA3, "Data/Benth_PC3.csv")



# check LMM
names(Benth_PCA3)
str(Benth_PCA3)

ggplot(Benth_PCA3, aes((Dim.4), log(Abund))) + geom_point()
ggplot(Benth_PCA3, aes((Depth_cm), log(Abund))) + geom_point()
ggplot(Benth_PCA3, aes((Macrophyte_biomass), log(Abund))) + geom_point()
ggplot(Benth_PCA3, aes((Fish_abundance), log(Abund))) + geom_point()

ggplot(Benth_PCA3, aes(x = System_type, y = log(Abund))) +
  geom_boxplot()

library(lme4) 
library(lmerTest)

m1 <- lmer(log(Abund) ~ # System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
             Natural_areas + 
           #  Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             (1|Country/Year/System_id),
           # (1|Random_effects), 
           data = Benth_PCA3)
# check multicolinearity
car::vif(m1) # <5 no multicolineatity detected

# check model
summary(m1)
car::Anova(m1)
anova(m1)
drop1(m1)

step(m1)

# assumptions
plot(m1)
qqnorm(resid(m1))
qqline(resid(m1))

m1.1 <- lmer(log(Abund) ~ Depth_cm + Macrophyte_biomass + (1 | Random_effects),  
             data = Benth_PCA3)
car::Anova(m1.1)
summary(m1.1)


ggplot(Benth_PCA3, aes((Abund), (SR))) + geom_point()

m2 <- lmer((SR) ~ #System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
             Natural_areas + 
             Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             # (1|Year/System_id),
             (1|Random_effects), 
           data = Benth_PCA3)

step(m2)


m2 <- glmer(SR ~  # Abund + 
            #  System_type +
                Dim.1 + Dim.2 + Dim.3 + Dim.4 +
               Natural_areas + 
            #  Depth_cm +
              Macrophyte_biomass + Fish_abundance +
              (1|Random_effects),  
            data = Benth_PCA3,
            family="poisson")


# check model
summary(m2)
car::vif(m2)
car::Anova(m2)
anova(m2)
drop1(m2)


# assumptions
plot(m2)
qqnorm(resid(m2))
qqline(resid(m2))




m3 <- lmer((H) ~  System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
             Natural_areas + 
             Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             # (1|Year/System_id),
             (1|Random_effects), 
           data = Benth_PCA3)
# check multicolinearity
car::vif(m3) # <5 no multicolineatity detected

# check model
summary(m3)
car::Anova(m3)
anova(m3)
drop1(m3)

step(m3)

# assumptions
plot(m3)
qqnorm(resid(m3))
qqline(resid(m3))



m4 <- lmer(log(FDis) ~  # System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
             Natural_areas + 
             Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             # (1|Year/System_id),
             (1|Random_effects), 
           data = Benth_PCA3)
# check multicolinearity
car::vif(m4) # <5 no multicolineatity detected

# check model
summary(m4)
car::Anova(m4)
anova(m4)
drop1(m4)

step(m4)

# assumptions
plot(m4)
qqnorm(resid(m4))
qqline(resid(m4))



ggplot(Benth_PCA3, aes((Fish_abundance), log(FRic))) + geom_point()

ggplot(Benth_PCA3, aes(x = System_type, y = log(FRic))) +
  geom_boxplot()

m4 <- lmer(log(FRic) ~ # System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
             Natural_areas + 
             Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             # (1|Year/System_id),
             (1|Random_effects), 
           data = Benth_PCA3)
# check multicolinearity
car::vif(m4) # <5 no multicolineatity detected

# check model
summary(m4)
car::Anova(m4)
anova(m4)
drop1(m4)

step(m4)

# assumptions
plot(m4)
qqnorm(resid(m4))
qqline(resid(m4))




m4 <- lmer(log(FRic) ~ System_type + Fish_abundance +
           (1|Random_effects), 
           data = Benth_PCA3)

summary(m4)
car::Anova(m4)



ggplot(Benth_PCA3, aes(x = System_type, y = RaoQ)) +
  geom_boxplot()

ggplot(Benth_PCA3, aes((Dim.4), (RaoQ))) + geom_point()
ggplot(Benth_PCA3, aes((Dim.2), (RaoQ))) + geom_point()


m4 <- lmer(log(RaoQ ) ~  # System_type +
             Dim.1 + Dim.2 + Dim.3 + Dim.4 +
            # Natural_areas + 
            # Depth_cm +
             Macrophyte_biomass + Fish_abundance +
             (1|Country/Year/System_id),
           #(1|Random_effects), 
           data = Benth_PCA3)
# check multicolinearity
car::vif(m4) # <5 no multicolineatity detected

# check model
summary(m4)
car::Anova(m4)


step(m4)
